version: "3.9"

services:
  personal-website:
    build:
      context: .
      secrets:
        - dbx_authorization_code
        - dbx_app_key
        - dbx_app_secret
        - dbx_access_token
        - dbx_refresh_token
        - personal_blog_secret
    ports:
      - "5000:8000"
    secrets:
      - dbx_authorization_code
      - dbx_app_key
      - dbx_app_secret
      - dbx_access_token
      - dbx_refresh_token
      - personal_blog_secret

secrets:
  dbx_authorization_code:
    file: .secrets/dbx_authorization_code
  dbx_app_key:
    file: .secrets/dbx_app_key
  dbx_app_secret:
    file: .secrets/dbx_app_secret
  dbx_access_token:
    file: .secrets/dbx_access_token
  dbx_refresh_token:
    file: .secrets/dbx_refresh_token
  personal_blog_secret:
    file: .secrets/personal_blog_secret
