name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/yunlanli/personal-blog:latest
            ghcr.io/yunlanli/personal-blog:${{ github.sha }}
          secrets: |
            dbx_app_key=${{ secrets.DROPBOX_APP_KEY }}
            dbx_app_secret=${{ secrets.DROPBOX_APP_SECRET }}
            dbx_access_token=${{ secrets.DROPBOX_ACCESS_TOKEN }}
            dbx_refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }}
            dbx_authorization_code=${{ secrets.DROPBOX_AUTHORIZATION_CODE }}
            personal_blog_secret=${{ secrets.MY_BLOG_SECRET_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.PS_SERVER_HOST }}
          username: ${{ secrets.PS_SERVER_USERNAME }}
          key: ${{ secrets.PS_SERVER_KEY }}
          script: |
            cd ~/personal-projects/personal-blog
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
            docker pull ghcr.io/yunlanli/personal-blog:latest
            docker-compose up -d
